### ISSUE TITLE
Sparklines updated?

### ISSUE THREAD

**Issue by jneubert** [gbv/cocoda-mappings#9]
The sparklines are a great way to illustrate the growth for a property or perhaps also a mapping.

However, it seems that they are not created anew after changes. (e.g., in the last days, I have [added lots of GND and RePEc ids](https://github.com/zbw/repec-ras/compare/d026dae...master#diff-25f10293200c12588a70979a6f838872), but the sparklines did not change).

**Comment by nichtich** [comment]
The growth is not visible because the graph started with zero and jumped to a high value, e.g. RePEc to 2213 at May 3rd. Should the sparklines show overall growth or recent growth only, e.g. the last two weeks? The current images are updated daily and have 80px width so a window of last 80 days would make sense.

**Comment by jneubert** [comment]
Perhaps make it 90 days (which mentally maps to three month)? If width is an issue, the date column could be made yyy-mm-dd (if the full timestamp is needed, it could be made a tooltip).

**Comment by jneubert** [comment]
Hmm - re. the RePEc graph: At what point in time did it start with zero? It was at ~1500 when I started working two month or so ago.

I suppose it would make sense to clean false zero values. That could give nice encouraging images like that about ORCID - instead of harshly demotivating ones :-)

**Comment by nichtich** [comment]
I modified the Sparklines to have 2 pixel width per day up to 40 days, without zero values for missing data. This limit has not been reached yet so we can have a second look after that. Additional info will be added as suggested in #10.
